apiVersion: v1
kind: Service
metadata:
  name: gin-basic
  labels:
    app: gin-basic
spec:
  type: NodePort
  selector:
    app: gin-basic
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
